services:
  app:
    build: .
    container_name: caseboticario
    image: case-boticario-image
    ports:
      - "8000:8000"
    volumes:
      - ./artefatos:/app/artefatos
      - ./dados/processed:/app/dados
    restart: always
